version: 2
jobs:
  test:
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test
      - run: npm run build

  docker_push_master:
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - setup_remote_docker
      - run: npm run docker:build
      - run: npm run docker:push

  docker_push_release:
    docker:
      # Node 8 LTS
      - image: circleci/node:carbon
    steps:
      - checkout
      - setup_remote_docker
      - run: npm run release:validate
      - run: npm run docker:build:release
      - run: npm run docker:push:release

workflows:
  version: 2
  build_and_push:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - docker_push_master:
          requires:
            - test
          filters:
            branches:
              only:
                - master
      - docker_push_release:
          requires:
            - test
          filters:
            tags:
              only: /.*/ # allow anything because tag syntax is validated as part of validate-release.sh
            branches:
              ignore: /.*/